In [1]:
import tensorflow as tf
import numpy

# Build Graph

In [2]:
#create 2 constant
a=tf.constant(value=[[1,2],[3,4]],name="constant_a")
b=tf.constant(value=[[1,1],[0,1]],name="constant_b")

In [3]:
#show a
a

<tf.Tensor 'constant_a:0' shape=(2, 2) dtype=int32>

In [4]:
type(a)

tensorflow.python.framework.ops.Tensor

In [5]:
#show b
b

<tf.Tensor 'constant_b:0' shape=(2, 2) dtype=int32>

In [6]:
#get c by a and b
c=tf.matmul(a,b)

In [7]:
#show c
c

<tf.Tensor 'MatMul:0' shape=(2, 2) dtype=int32>

In [8]:
sess=tf.Session()

# attribute test

In [9]:
#device
a.device

''

In [10]:
#dtype
a.dtype

tf.int32

In [11]:
#graph
a.graph

In [12]:
#name
a.name

'constant_a:0'

In [13]:
#op
a.op

<tf.Operation 'constant_a' type=Const>

In [14]:
#shape
a.shape

TensorShape([Dimension(2), Dimension(2)])

In [15]:
#value_index
a.value_index

0

In [16]:
b.value_index

0

In [17]:
c.op

<tf.Operation 'MatMul' type=MatMul>

# overwrite method test

In [20]:
#__abs__
sess.run(abs(a))

array([[1, 2],
       [3, 4]], dtype=int32)

In [21]:
#__add__(broadcasting)
sess.run(a+b)

array([[2, 3],
       [3, 5]], dtype=int32)

In [33]:
#__sub__
sess.run(a-b)

array([[0, 1],
       [3, 3]], dtype=int32)

In [22]:
#__div__
sess.run(a/2)

array([[ 0.5,  1. ],
       [ 1.5,  2. ]])

In [29]:
#__getitem__(index)
sess.run(a[1,1])

4

In [26]:
#__eq__
a==b,a!=b

(False, True)

In [28]:
#__ge__(GreaterEqual)
sess.run(a>=b)

array([[ True,  True],
       [ True,  True]], dtype=bool)

In [30]:
#__gt__
sess.run(a>b)

array([[False,  True],
       [ True,  True]], dtype=bool)

In [31]:
#__le__
sess.run(a<=b)

array([[ True, False],
       [False, False]], dtype=bool)

In [32]:
#__lt__
sess.run(a<b)

array([[False, False],
       [False, False]], dtype=bool)

In [34]:
#__mul__(mult element-wise)
sess.run(a*b)

array([[1, 2],
       [0, 4]], dtype=int32)

In [35]:
#__matmul__(Matrix multiple)
sess.run(a@b)

array([[1, 3],
       [3, 7]], dtype=int32)

In [36]:
#__neg__
sess.run(-a)

array([[-1, -2],
       [-3, -4]], dtype=int32)

# method test

In [37]:
#consumers
a.consumers()

[<tf.Operation 'MatMul' type=MatMul>,
 <tf.Operation 'Abs' type=Abs>,
 <tf.Operation 'add' type=Add>,
 <tf.Operation 'truediv/Cast' type=Cast>,
 <tf.Operation 'GreaterEqual' type=GreaterEqual>,
 <tf.Operation 'GreaterEqual_1' type=GreaterEqual>,
 <tf.Operation 'strided_slice' type=StridedSlice>,
 <tf.Operation 'Greater' type=Greater>,
 <tf.Operation 'LessEqual' type=LessEqual>,
 <tf.Operation 'Less' type=Less>,
 <tf.Operation 'sub' type=Sub>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'matmul' type=MatMul>,
 <tf.Operation 'Neg' type=Neg>]

In [38]:
#eval
a.eval(session=sess)

array([[1, 2],
       [3, 4]], dtype=int32)

In [39]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])