In [2]:
import tensorflow as tf
import numpy as np


# pattern we always used

In [3]:
#define graph
w=tf.Variable(initial_value=[[1,2],[3,4]],dtype=tf.float32,name="w")
x=tf.Variable(initial_value=[[1,0],[0,1]],dtype=tf.float32,name="x")

In [4]:
#like Tensor
y=tf.matmul(w,x,name="y")

In [5]:
#y,two variables can produce a Tensor
y

<tf.Tensor 'y:0' shape=(2, 2) dtype=float32>

In [6]:
#w
w

<tf.Variable 'w:0' shape=(2, 2) dtype=float32_ref>

In [7]:
#before you really use the variables,you should add a initial opration
init_op=tf.global_variables_initializer()

In [8]:
#define session
sess=tf.Session()

In [9]:
#run init_op first
sess.run(fetches=init_op)

In [10]:
sess.run(fetches=w)

array([[ 1.,  2.],
       [ 3.,  4.]], dtype=float32)

In [11]:
sess.run(fetches=x)

array([[ 1.,  0.],
       [ 0.,  1.]], dtype=float32)

In [12]:
sess.run(fetches=y)

array([[ 1.,  2.],
       [ 3.,  4.]], dtype=float32)

# attribute test

In [13]:
#device
w.device

''

In [14]:
#dtype
w.dtype

tf.float32_ref

In [15]:
#graph
w.graph

In [16]:
#initial_value
w.initial_value

<tf.Tensor 'w/initial_value:0' shape=(2, 2) dtype=float32>

In [17]:
sess.run(w.initial_value)

array([[ 1.,  2.],
       [ 3.,  4.]], dtype=float32)

In [18]:
#initializer
w.initializer

<tf.Operation 'w/Assign' type=Assign>

In [19]:
#name
w.name

'w:0'

In [20]:
#op
w.op

<tf.Operation 'w' type=VariableV2>

In [21]:
#shape
w.shape

TensorShape([Dimension(2), Dimension(2)])

# overwrite method test

In [22]:
#__abs__
sess.run(abs(w))

array([[ 1.,  2.],
       [ 3.,  4.]], dtype=float32)

In [23]:
#__add__ (broadcasting)
sess.run(w+y)

array([[ 2.,  4.],
       [ 6.,  8.]], dtype=float32)

In [24]:
#__and__
sess.run(w and y)

array([[ 1.,  2.],
       [ 3.,  4.]], dtype=float32)

In [25]:
#__div__
sess.run(w/2)

array([[ 0.5,  1. ],
       [ 1.5,  2. ]], dtype=float32)

In [26]:
#__getitem__
sess.run(w[1,1])

4.0

In [27]:
#there also have a lot of method overwrited,and same as Tensor.\
#you can get it in doc

# method test

In [28]:
#assign(),change the value of variable and return a tensor
t1=w.assign(value=[[-1,-1],[-1,-1]])
sess.run(t1)

array([[-1., -1.],
       [-1., -1.]], dtype=float32)

In [29]:
#assign_add()
t2=w.assign_add(delta=[[1,1],[1,1]])
sess.run(t2)


array([[ 0.,  0.],
       [ 0.,  0.]], dtype=float32)

In [30]:
#assign_sub()
t3=w.assign_sub(delta=[[2,2],[2,2]])
sess.run(t3)

array([[-2., -2.],
       [-2., -2.]], dtype=float32)

In [33]:
#count_up_to
t4=w.count_up_to(6)
sess.run(t4)

TypeError: Value passed to parameter 'ref' has DataType float32 not in list of allowed values: int32, int64

In [34]:
#get_shape()
w.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [39]:
#initialized_value
t5=w.initialized_value()
sess.run(t5)

array([[-2., -2.],
       [-2., -2.]], dtype=float32)

In [40]:
#read_value
t6=w.read_value()
sess.run(t6)

array([[-2., -2.],
       [-2., -2.]], dtype=float32)

In [45]:
#scatter_sub


In [48]:
#set_shape()
