In [1]:
import tensorflow as tf
import numpy as np

In [2]:
#graph
g=tf.Graph()
#session
sess=tf.Session(graph=g)

# tf.random_normal

In [3]:
with g.as_default():
    t_random_normal=tf.random_normal(shape=(3,3),mean=1.0,stddev=4)

In [4]:
sess.run(t_random_normal)

array([[-2.74477148,  4.70928335,  8.96044254],
       [ 4.94794559,  6.90424538,  1.06358719],
       [ 6.2819438 ,  4.21028662, -7.50055599]], dtype=float32)

# tf.truncated_normal

In [5]:
with g.as_default():
    t_truncated_normal=tf.truncated_normal(shape=(3,3),mean=1.0,stddev=4)

In [6]:
sess.run(t_truncated_normal)

array([[-0.57156932, -2.0348475 ,  4.00824833],
       [-3.48432589,  1.48540568, -0.91829348],
       [-2.2413311 , -1.04811025, -0.80578125]], dtype=float32)

# tf.random_uniform

In [7]:
with g.as_default():
    t_random_uniform=tf.random_uniform(shape=(3,3),minval=4,maxval=10)

In [8]:
sess.run(t_random_uniform)

array([[ 7.44613218,  9.54999542,  5.9197464 ],
       [ 6.72255898,  7.49471092,  4.87040138],
       [ 6.74538898,  8.92973328,  5.48186779]], dtype=float32)

# tf.random_shuffle

In [9]:
with g.as_default():
    t_random_shuffle=tf.random_shuffle(t_random_normal)

In [10]:
sess.run(t_random_shuffle)

array([[-10.17941093,  -1.09409261,   3.9549489 ],
       [ -2.00940132,   4.34156752,   0.76062202],
       [ -2.84134674,  -1.55259609,   5.06359577]], dtype=float32)